FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV DEBUG=false
ENV OVERPASS_URL="http://overpass"
ENV TILE_ZOOM_RANGE="[18,18]"
ENV TILE_RUNTIME_CONFIG_FILE="/app/runtime-config.json"
ENV TILE_API_KEYS=""
ENV ALLOWED_EDITOR_EMAILS=""
ENV KEYCLOAK_REALM=""
ENV KEYCLOAK_URL=""
ENV KEYCLOAK_SSL_REQUIRED="external"
ENV KEYCLOAK_CLIENT_ID=""
ENV KEYCLOAK_CLIENT_SECRET=""
ENV KEYCLOAK_CONFIDENTIAL_PORT=0

COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts

COPY . .

RUN mkdir -p cache

EXPOSE 3000

CMD ["node", "server.js"]
